#### 1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

In [2]:
import numpy as np
li = [1,2,3,4,5]
arr = np.array(li)
arr


array([1, 2, 3, 4, 5])

#### 2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
Expected Output: [[ 2 3 4][ 5 6 7][ 8 9 10]]

In [8]:
import numpy as np
arr = np.arange(2,11)
arr.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

#### 3. Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.
Sample Array [
[-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]
Expected Output:
Values in Fahrenheit degrees:
[ 0. 12. 45.21 34. 99.91 32. ]
Values in Centigrade degrees:
[-17.78 -11.11 7.34 1.11 37.73 0. ]

In [14]:
import numpy as np
li = [-17.78,-11.11,7.34,1.11,37.73,0]
arrc = np.array(li)
for i in arrc:
    i = (i*9/5) + 32
    print(i)

-0.0040000000000048885
12.002000000000002
45.212
33.998
99.914
32.0


#### 4. Shown below is the input NumPy array. Delete column two and replace it with the new column given below.

import NumPy

sampleArray = NumPy.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = NumPy.array([[10,10,10]])

In [24]:
import numpy as np
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
arr
col2 = np.array([10,10,10])
for i in range(len(arr[1])):
    arr[1][i] = col2[i]

arr

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])