## How to Create Array

In [9]:
import numpy as np
list = [1,8,7,4,6,7]
array = np.array(list)
print(array)

[1 8 7 4 6 7]


In [13]:
import numpy as np
list = []
size = int(input("Enter the size of the list"))
for i in range (0, size):
    val = int(input("Enter {}'s value".format(i)))
    list.append(val)
print(list)
array = np.array(list)
array

Enter the size of the list 5
Enter 0's value 1
Enter 1's value 2
Enter 2's value 3
Enter 3's value 4
Enter 4's value 5


[1, 2, 3, 4, 5]


array([1, 2, 3, 4, 5])

## Numpy Functions

In [8]:
import numpy as np
array = np.zeros((5,5))
array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
import numpy as np
array = np.ones((5,5))
array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
import numpy as np
array = np.eye(5,5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
import numpy as np
array = np.diag([1,2,3,4,5])
array

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [14]:
import numpy as np
array = np.diag([1,2,3,4,5], 2)
array

array([[0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [16]:
import numpy as np
array = np.random.randint(1,6,5)
array

array([5, 4, 1, 2, 3])

In [17]:
import numpy as np
array = np.random.randint(1,6,(3,3))
array

array([[3, 4, 4],
       [3, 1, 5],
       [1, 4, 2]])

In [18]:
import numpy as np
array = np.random.rand(5)
array

array([0.86382765, 0.43928707, 0.25194191, 0.10205458, 0.45730567])

In [20]:
import numpy as np
array = np.random.randn(5)
array

array([ 1.0638821 ,  0.99330627,  0.59892522,  0.23475577, -1.29658531])

## 2D Array

In [1]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
print(array[0,2])

3


In [7]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
print(array[0, 0:2])

[1 2]


## Seed

In [16]:
import numpy as np
np.random.seed(1)
arr = np.random.randint(1, 100, 10)
arr

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

## Create 2d Arrayfom user's inpput

In [45]:
import numpy as np
li = []
row = int(input("Enter No. of rows: "))
col = int(input("Enter No. of coulms: "))
for i in range(row):
    x = []
    for j in range(col):
        val = int(input("Enter {},{} value: ".format(i, j)))
        x.append(val)
    li.append(x)
    
arr = np.array(li)
arr

Enter No. of rows:  3
Enter No. of coulms:  3
Enter 0,0 value:  1
Enter 0,1 value:  2
Enter 0,2 value:  3
Enter 1,0 value:  4
Enter 1,1 value:  5
Enter 1,2 value:  6
Enter 2,0 value:  7
Enter 2,1 value:  8
Enter 2,2 value:  9


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])